//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vacation
    {
        public int ID { get; set; }
        public string vacationDuration { get; set; }
        public string vacationStartDay { get; set; }
        public string vacationEndDay { get; set; }
        public Nullable<int> employee_id { get; set; }
        public string employeeTier { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
